version: "3"
services:
  web:
    build: .
    ports:
      - "3030:3030"

    volumes: 
      - webserver:/store
    links:
      - postgres
    environment: 
      - STORAGE_PATH=/store
      - DATABASE_URL=postgres://postgres:password@postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=password
volumes:
  webserver: {}
